
export default class CommonConstants {
  /**
   * Number 2.
   */
  static readonly NUMBER_TWO: number = 2;
  /**
   * Number 3.
   */
  static readonly NUMBER_THREE: number = 3;
  /**
   * Number 4.
   */
  static readonly NUMBER_FOUR: number = 4;
  /**
   * Number 10.
   */
  static readonly NUMBER_TEN: number = 4;
  /**
   * Default size of the watch face.
   */
  static readonly DEFAULT_WATCH_SIZE: number = 300;
  /**
   * Default size of the watch face.
   */
  static readonly DEFAULT_WATCH_RADIUS: number = 150;
  /**
   * Full percentage.
   */
  static readonly FULL_PERCENTAGE: string = '100%';
  /**
   * Interval time.
   */
  static readonly INTERVAL_TIME: number = 1000;
  /**
   * Canvas height add.
   */
  static readonly HEIGHT_ADD: number = 150;
  /**
   * Conversion rate.
   */
  static readonly CONVERSION_RATE: number = 0.6;
  /**
   * Hours string.
   */
  static readonly HOURS: Array<string> = ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '1', '2'];


  static readonly MAX_HOUR_NUMBER: number = 24;

  static readonly MAX_MIN_NUMBER: number = 60;

  static readonly MAX_SEC_NUMBER: number = 60;
  static readonly FONT_WEIGHT_TAB: number = 250;
  static readonly ANIMATION_DURATION: number = 300;

  /**
   * Percent zero.
   */
  static readonly PERCENT_ZERO: string = '0%';

  /**
   * Percent half.
   */
  static readonly PERCENT_HALF: string = '50%';
  static readonly PERCENT_MAX: string = '100%';
  /**
   * Timer delay.
   */
  static readonly TIMER_DELAY: number = 1000;

  /**
   * Animate duration.
   */
  static readonly ANIMATE_DURATION: number = 200;

  /**
   * Rotate angle.
   */
  static readonly ROTATE_ANGLE: number = -90;

  static readonly LIST_HEIGHT: number = 48;
  static readonly FULL_WIDTH: string = '100%';
  static readonly DIVIDER_HEIGHT: number = 0.5;
  static readonly DIVIDER_DRAWER_WIDTH: string = '90%';
  static readonly DIVIDER_WIDTH: string = '93%';
  static readonly DRAWER_WIDTH: number = 264;
  static readonly BORDER_RADIUS_DRAWER: number = 16;
  static readonly LIST_IMAGE_HEIGHT_WIDTH: number = 40;
  static readonly LIST_CARD_WIDTH: number = 272;
  static readonly LIST_CARD_HEIGHT: number = 344;
  static readonly BORDER_RADIUS_DRAWER_CONTENT: number = 20;
  static readonly FULL_HEIGHT: string = '100%';
  static readonly LIST_CONTENT_HEIGHT: string = '110%';
  static readonly MARGIN_SIXTEEN: number = 16;
  static readonly MARGIN_BUTTON_TOP: number = 48;
  static readonly SUB_LIST_WIDTH: string = '85%';
  static readonly TRANSLATE_TOP: number = -40;


}