/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Common constants for all features.
 */
export default class CommonConstants {
  /**
   * Number 2.
   */
  static readonly NUMBER_TWO: number = 2;
  /**
   * Number 3.
   */
  static readonly NUMBER_THREE: number = 3;
  /**
   * Number 4.
   */
  static readonly NUMBER_FOUR: number = 4;
  /**
   * Number 10.
   */
  static readonly NUMBER_TEN: number = 4;
  /**
   * Default size of the watch face.
   */
  static readonly DEFAULT_WATCH_SIZE: number = 300;
  /**
   * Default size of the watch face.
   */
  static readonly DEFAULT_WATCH_RADIUS: number = 150;
  /**
   * Full percentage.
   */
  static readonly FULL_PERCENTAGE: string = '100%';
  /**
   * Interval time.
   */
  static readonly INTERVAL_TIME: number = 1000;
  /**
   * Canvas height add.
   */
  static readonly HEIGHT_ADD: number = 150;
  /**
   * Conversion rate.
   */
  static readonly CONVERSION_RATE: number = 0.6;
  /**
   * Hours string.
   */
  static readonly HOURS: Array<string> = ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '1', '2'];


  static readonly MAX_HOUR_NUMBER: number = 24;

  static readonly MAX_MIN_NUMBER: number = 60;

  static readonly MAX_SEC_NUMBER: number = 60;
  static readonly FONT_WEIGHT_TAB: number = 250;
  static readonly ANIMATION_DURATION: number = 300;

  /**
   * Percent zero.
   */
  static readonly PERCENT_ZERO: string = '0%';

  /**
   * Percent half.
   */
  static readonly PERCENT_HALF: string = '50%';
  static readonly PERCENT_MAX: string = '100%';
  /**
   * Timer delay.
   */
  static readonly TIMER_DELAY: number = 1000;

  /**
   * Animate duration.
   */
  static readonly ANIMATE_DURATION: number = 600;

  /**
   * Rotate angle.
   */
  static readonly ROTATE_ANGLE: number = -90;
}